Support custom spec sources
Arnavion/k8s-openapi pull request #90
Opened 2021-04-16 12:21 UTC by MikailBag

Usage example:
```bash
kubectl proxy &
cd k8s-openapi-codegen
VERSIONS=v1.20=http://127.0.0.1:8001/openapi/v2 cargo run
```
This change is not useful on its own, but it eventually it should allow support non-builtin API groups, such as `metrics.k8s.io`.

I have not written any documentation yet. What is the best location for docs?

2021-04-16 17:41 UTC, Arnavion commented
>I have not written any documentation yet. What is the best location for docs?

Well `-codegen` has been an "internal" tool up to this point, with the other crates being the point of the repo. But we can change that of course.

Just add it to `k8s-openapi-codegen/README.md`

>To summarize, using the `VERSIONS` environment variable user can:

It would be better to take it as CLI args:

```sh
# Generate all with built-in URLs
k8s-openapi-codegen

# Only generate 1.19 and 1.20 with built-in URLs
k8s-openapi-codegen --generate 1.19 --generate 1.20

# Only generate 1.19 and 1.20, and override URL for 1.20
k8s-openapi-codegen --generate 1.19 --generate 1.20:http://foo.bar/spec.json
```

(Use `structopt` please.)

2021-04-16 17:46 UTC, Arnavion requested changes

2021-04-16 17:46 UTC, Arnavion commented on k8s-openapi-codegen/src/main.rs
> +		for ver in supported_version::ALL.iter().copied() {
```rust
if let Some(&ver) = supported_version::ALL.iter().find(|&ver| ver.name() == name) {
```

2021-04-16 17:46 UTC, Arnavion commented on k8s-openapi-codegen/src/main.rs
> +			panic!("unknown requested version");
Return an `Err()` like the rest of the code, and include `{:?}` of `found_version` in the message.

2021-04-16 17:46 UTC, Arnavion commented on k8s-openapi-codegen/src/main.rs
> +fn run(supported_version: supported_version::SupportedVersion, out_dir_base: &std::path::Path, client: &reqwest::blocking::Client, spec_url_override: Option<&str>) -> Result<(), Error> {
Just take `spec_url: &str` and make the caller specify either the default from `SupportedVersion::spec_url` or the user one.

2021-04-19 06:45 UTC, Arnavion commented
I fixed a few things and pushed to https://github.com/Arnavion/k8s-openapi/compare/pr/90

- Some incorrect whitespace - spaces indentation, trailing whitespace.

- The `--version` parsing was broken because it expected the parameter to contain the `v` prefix. Since `--version=v1.20` would look redundant, I changed the `SupportedVersion::name()` function to not have the `v` prefix.

- The `--version` parsing was broken because it used `split(':')` instead of `splitn(2, ':')`, so URLs would truncate after the protocol and be invalid.

- Tweaked the helptext and error message to be more explanatory.

Does that branch look okay to you?

2021-04-19 10:02 UTC, MikailBag commented
> Does that branch look okay to you?

Yes, sure. Thanks for your review and fixes.

2021-04-20 03:27 UTC, closed without merging